import { Injectable } from '@angular/core';
import {municipiosinterface, registrointerface} from "./interface-registro";

@Injectable({
  providedIn: 'root'
})
export class DataService {

/*Array para los estados*/
  public estados1: registrointerface[]=
    [
      {id: 1, nombreE: 'Aguascalientes'},
      {id:2,  nombreE: 'Baja California'},
      {id:3,  nombreE: 'Baja California Sur',},
      {id:4,  nombreE: 'Campeche',},
      {id:5,  nombreE: 'Coahuila',},
      {id:6,  nombreE: 'Colima',},
      {id:7,  nombreE: 'Chiapas',},
      {id:8,  nombreE: 'Chihuahua',},
      {id:9,  nombreE: 'Ciudad de México',},
      {id:10, nombreE: 'Durango',},
      {id:11, nombreE: 'Guerrero',},
      {id:12, nombreE: 'Guanajuato',},
      {id:13, nombreE: 'Hidalgo',},
      {id:14, nombreE: 'Jalisco',},
      {id:15, nombreE: 'Michoacan',},
      {id:16, nombreE: 'Estado de México',},
      {id:17, nombreE: 'Morelos',},
      {id:18, nombreE: 'Nayarit',},
      {id:19, nombreE: 'Nuevo Leon',},
      {id:20, nombreE: 'Oaxaca',},
      {id:21, nombreE: 'Puebla',},
      {id:22, nombreE: 'Quintana Roo',},
      {id:23, nombreE: 'Queretaro',},
      {id:24, nombreE: 'Sinaloa',},
      {id:25, nombreE: 'San Luis Potosi',},
      {id:26, nombreE: 'Sonora',},
      {id:27, nombreE: 'Tabasco',},
      {id:28, nombreE: 'Tlaxcala',},
      {id:29, nombreE: 'Tamaulipas',},
      {id:30, nombreE: 'Veracruz',},
      {id:31, nombreE: 'Yucatan',},
      {id:32, nombreE: 'Zacatecas',}
    ]
  /*Array para los municipios*/
  public municipios1: municipiosinterface[]=[
    //Aguascalientes
    {id:1,idm:1,nombrem: 'Aguascalientes',},
    {id:1, idm:2, nombrem: 'Asientos',},
    {id:1, idm:3, nombrem: 'Calvillo',},
    {id:1, idm:4, nombrem: 'Cosio',},
    {id:1, idm:5, nombrem: 'El Llano',},
    {id:1, idm:6, nombrem: 'Jesus Maria',},
    {id:1, idm:7, nombrem: 'Pabellon de Arteaga',},
    {id:1, idm:8, nombrem: 'Rincon de Romos',},
    {id:1, idm:9, nombrem: 'San Francisco de los Romo',},
    {id:1, idm:10,nombrem: 'San Jose de Gracia',},
    {id:1, idm:11,nombrem: 'Tepezala',},
    //Baja California
    {id:2,idm:1,nombrem: 'Ensenada',},
    {id:2,idm:2,nombrem: 'Mexicali',},
    {id:2, idm:3, nombrem: 'Playas de Rosarito',},
    {id:2, idm:4, nombrem: 'Tecate',},
    {id:2, idm:5, nombrem: 'Tijuana',},
    {id:3, idm:1, nombrem: 'Comondu',},
    {id:3, idm:2, nombrem: 'La Paz',},
    {id:3, idm:3, nombrem: 'Loreto',},
    {id:3, idm:4, nombrem: 'Los Cabos',},
    {id:3, idm:5, nombrem: 'Mulege',},
    //Campeche
    {id:4, idm:1, nombrem: 'Calakmul',},
    {id:4, idm:2, nombrem: 'Calkini',},
    {id:4, idm:3, nombrem: 'Campeche',},
    {id:4, idm:4, nombrem: 'Candelaria',},
    {id:4, idm:5, nombrem: 'Carmen',},
    {id:4, idm:6, nombrem: 'Champoton',},
    {id:4, idm:7, nombrem: 'Escarcega',},
    {id:4, idm:8, nombrem: 'Hecelchakan',},
    {id:4, idm:9, nombrem: 'Hopelchen',},
    {id:4, idm:10, nombrem: 'Palizada',},
    {id:4, idm:11, nombrem: 'Tenabo',},
    //Coahuila
    {id:5, idm:1, nombrem: 'Abasolo',},    {id:5, idm:2, nombrem: 'Acuna',},
    {id:5, idm:3, nombrem: 'Allende',},    {id:5, idm:4, nombrem: 'Arteaga',},
    {id:5, idm:5, nombrem: 'Candela',},    {id:5, idm:6, nombrem: 'Castanos',},
    {id:5, idm:7, nombrem: 'Cuatro Cienegas',},    {id:5, idm:8, nombrem: 'Escobedo',},
    {id:5, idm:9, nombrem: 'Francisco I. Madero',},    {id:5, idm:10, nombrem: 'Frontera',},
    {id:5, idm:11, nombrem: 'General Cepeda',},    {id:5, idm:12, nombrem: 'Guerrero',},
    {id:5, idm:13, nombrem: 'Hidalgo',},    {id:5, idm:14, nombrem: 'Jimenez',},
    {id:5, idm:15, nombrem: 'Juarez',},    {id:5, idm:16, nombrem: 'Lamadrid',},
    {id:5, idm:17, nombrem: 'Matamoros',},    {id:5, idm:18, nombrem: 'Monclova',},
    {id:5, idm:19, nombrem: 'Morelos',},    {id:5, idm:20, nombrem: 'Muzquiz',},
    {id:5, idm:21, nombrem: 'Nadadores',},    {id:5, idm:22, nombrem: 'Nava',},
    {id:5, idm:23, nombrem: 'Ocampo',},    {id:5, idm:24, nombrem: 'Parras',},
    {id:5, idm:25, nombrem: 'Piedras Negras',},    {id:5, idm:26, nombrem: 'Progreso',},
    {id:5, idm:27, nombrem: 'Ramos Arizpe',},    {id:5, idm:28, nombrem: 'Sabinas',},
    {id:5, idm:29, nombrem: 'Sacramento',},    {id:5, idm:30, nombrem: 'Saltillo',},
    {id:5, idm:31, nombrem: 'San Buenaventura',},    {id:5, idm:32, nombrem: 'San Juan de Sabinas',},
    {id:5, idm:33, nombrem: 'San Pedro',},    {id:5, idm:34, nombrem: 'Sierra Mojada',},
    {id:5, idm:35, nombrem: 'Torreon',},    {id:5, idm:36, nombrem: 'Viesca',},
    {id:5, idm:37, nombrem: 'Villa Union',},    {id:5, idm:38, nombrem: 'Zaragoza',},
    //Colima
    {id:6, idm: 1, nombrem: 'Armeria',},
    {id:6, idm: 2, nombrem: 'Colima',},
    {id:6, idm: 3, nombrem: 'Comala',},
    {id:6, idm: 4, nombrem: 'Coquimatlan',},
    {id:6, idm: 5, nombrem: 'Cuauhtemoc',},
    {id:6, idm: 6, nombrem: 'Ixtlahuacan',},
    {id:6, idm: 7, nombrem: 'Manzanillo',},
    {id:6, idm: 8, nombrem: 'Minatitlan',},
    {id:6, idm: 9, nombrem: 'Tecoman',},
    {id:6, idm: 10, nombrem: 'Villa de Alvarez',},
    //Chiapas
    {id:7, idm: 1, nombrem: 'Acacoyagua',},    {id:7, idm: 2, nombrem: 'Acala',},    {id:7, idm: 3, nombrem: 'Acapetahua',},
    {id:7, idm: 4, nombrem: 'Aldama',},    {id:7, idm: 5, nombrem: 'Altamirano',},    {id:7, idm: 6, nombrem: 'Amatenango de la Frontera',},
    {id:7, idm: 7, nombrem: 'Amatenango del Valle',},    {id:7, idm: 8, nombrem: 'Amatan',},    {id:7, idm: 9, nombrem: 'Angel Albino Corzo',},
    {id:7, idm: 10, nombrem: 'Arriaga',},    {id:7, idm: 11, nombrem: 'Bejucal de Ocampo',},    {id:7, idm: 12, nombrem: 'Bella Vista',},
    {id:7, idm: 13, nombrem: 'Benemerito de las Americas',},    {id:7, idm: 14, nombrem: 'Berriozabal',},    {id:7, idm: 15, nombrem: 'Bochil',},
    {id:7, idm: 16, nombrem: 'Cacahoatan',},    {id:7, idm: 17, nombrem: 'Capitan Luis Angel Vidal',},    {id:7, idm: 18, nombrem: 'Catazaja',},
    {id:7, idm: 19, nombrem: 'Chalchihuitan',},    {id:7, idm: 20, nombrem: 'Chamula',},    {id:7, idm: 21, nombrem: 'Chanal',},
    {id:7, idm: 22, nombrem: 'Chapultenango',},    {id:7, idm: 23, nombrem: 'Chenalho',},    {id:7, idm: 24, nombrem: 'Chiapa de Corzo',},
    {id:7, idm: 25, nombrem: 'Chiapilla',},    {id:7, idm: 26, nombrem: 'Chicoasen',},    {id:7, idm: 27, nombrem: 'Chicomuselo',},
    {id:7, idm: 28, nombrem: 'Chilon',},    {id:7, idm: 29, nombrem: 'Cintalapa',},    {id:7, idm: 30, nombrem: 'Coapilla',},
    {id:7, idm: 31, nombrem: 'Comitan de Dominguez',},    {id:7, idm: 32, nombrem: 'Copainala',},    {id:7, idm: 33, nombrem: 'El Bosque',},
    {id:7, idm: 34, nombrem: 'El Parral',},    {id:7, idm: 35, nombrem: 'El Porvenir',},    {id:7, idm: 36, nombrem: 'Emiliano Zapata',},
    {id:7, idm: 37, nombrem: 'Escuintla',},    {id:7, idm: 38, nombrem: 'Francisco Leon',},    {id:7, idm: 39, nombrem: 'Frontera Comalapa',},
    {id:7, idm: 40, nombrem: 'Frontera Hidalgo',},    {id:7, idm: 41, nombrem: 'Huehuetan',},    {id:7, idm: 42, nombrem: 'Huitiupan',},
    {id:7, idm: 43, nombrem: 'Huixtla',},    {id:7, idm: 44, nombrem: 'Huixtan',},    {id:7, idm: 45, nombrem: 'Ixhuatan',}, {id:7, idm: 46, nombrem: 'Ixtacomitan',},
    {id:7, idm: 47, nombrem: 'Ixtapa',},    {id:7, idm: 48, nombrem: 'Ixtapangajoya',},    {id:7, idm: 49, nombrem: 'Jiquipilas',},
    {id:7, idm: 50, nombrem: 'Jitotol',},    {id:7, idm: 51, nombrem: 'Juarez',},    {id:7, idm: 52, nombrem: 'La Concordia',},
    {id:7, idm: 53, nombrem: 'La Grandeza',},    {id:7, idm: 54, nombrem: 'La Independencia',},    {id:7, idm: 55, nombrem: 'La Libertad',},
    {id:7, idm: 56, nombrem: 'La Trinitaria',},    {id:7, idm: 57, nombrem: 'Larrainzar',},    {id:7, idm: 58, nombrem: 'Las Margaritas',},
    {id:7, idm: 59, nombrem: 'Las Rosas',},    {id:7, idm: 60, nombrem: 'Mapastepec',},    {id:7, idm: 61, nombrem: 'Maravilla Tenejapa',},
    {id:7, idm: 62, nombrem: 'Marques de Comillas',},    {id:7, idm: 63, nombrem: 'Mazapa de Madero',},    {id:7, idm: 64, nombrem: 'Mazatan',},
    {id:7, idm: 65, nombrem: 'Metapa',},    {id:7, idm: 66, nombrem: 'Mezcalapa',},    {id:7, idm: 67, nombrem: 'Mitontic',},
    {id:7, idm: 68, nombrem: 'Montecristo de Guerrero',},    {id:7, idm: 69, nombrem: 'Motozintla',},    {id:7, idm: 70, nombrem: 'Nicolas Ruiz',},
    {id:7, idm: 71, nombrem: 'Ocosingo',},    {id:7, idm: 72, nombrem: 'Ocotepec',},    {id:7, idm: 73, nombrem: 'Ocozocoautla de Espinosa',},
    {id:7, idm: 74, nombrem: 'Ostuacan',},    {id:7, idm: 75, nombrem: 'Osumacinta',},    {id:7, idm: 76, nombrem: 'Oxchuc',},
    {id:7, idm: 77, nombrem: 'Palenque',},    {id:7, idm: 78, nombrem: 'Pantelho',},    {id:7, idm: 79, nombrem: 'Pantepec',},{id:7, idm: 80, nombrem: 'Pichucalco',}
    ,{id:7, idm: 81, nombrem: 'Pijijiapan',},{id:7, idm: 82, nombrem:'Pueblo Nuevo Solistahuacan',},{id:7, idm: 83, nombrem:'Rayon',}
    ,{id:7, idm: 84, nombrem:'Reforma',},{id:7, idm: 85, nombrem:'Rincon Chamula San Pedro',},{id:7, idm: 86, nombrem:'Sabanilla',}
    ,{id:7, idm: 87, nombrem:'Salto de Agua',},{id:7, idm: 88, nombrem:'San Andres Duraznal',},{id:7, idm: 89, nombrem:'San Cristobal de las Casas',}
    ,{id:7, idm: 90, nombrem:'San Fernando',},{id:7, idm: 91, nombrem:'San Juan Cancuc',},{id:7, idm: 92, nombrem:'San Lucas',}
    ,{id:7, idm: 93, nombrem:'Santiago el Pinar',},{id:7, idm: 94, nombrem:'Siltepec',},{id:7, idm: 95, nombrem:'Simojovel',}
    ,{id:7, idm: 96, nombrem:'Sitala',},{id:7, idm: 97, nombrem:'Socoltenango',},{id:7, idm: 98, nombrem:'Solosuchiapa',}
    ,{id:7, idm: 99, nombrem:'Soyalo',},{id:7, idm: 100, nombrem:'Suchiapa',},{id:7, idm: 101, nombrem:'Suchiate',}
    ,{id:7, idm: 102, nombrem:'Sunuapa',},{id:7, idm: 103, nombrem:'Tapachula',},{id:7, idm: 104, nombrem:'Tapalapa',}
    ,{id:7, idm: 105, nombrem:'Tapilula',},{id:7, idm: 106, nombrem:'Tecpatan',},{id:7, idm: 107, nombrem:'Tenejapa',}
    ,{id:7, idm: 108, nombrem:'Teopisca',},{id:7, idm: 109, nombrem:'Tila',},{id:7, idm: 110, nombrem:'Tonala',}
    ,{id:7, idm: 111, nombrem:'Totolapa',},{id:7, idm: 112, nombrem:'Tumbala',},{id:7, idm: 113, nombrem:'Tuxtla Chico',}
    ,{id:7, idm: 114, nombrem:'Tuxtla Gutierrez',},{id:7, idm: 115, nombrem:'Tuzantan',},{id:7, idm: 116, nombrem:'Tzimol',}
    ,{id:7, idm: 117, nombrem:'Union Juarez',},{id:7, idm: 118, nombrem:'Venustiano Carranza',},{id:7, idm: 119, nombrem:'Villa Comaltitlan',}
    ,{id:7, idm: 120, nombrem:'Villa Corzo',},{id:7, idm: 121, nombrem:'Villaflores',},{id:7, idm: 122, nombrem:'Yajalon',}
    ,{id:7, idm: 123, nombrem:'Zinacantan',},
    //Chihuahua
    {id:8, idm: 1, nombrem:'Ahumada'},{id:8, idm: 2, nombrem:'Aldama'},{id:8, idm: 3, nombrem:'Allende'},
    {id:8, idm: 4, nombrem:'Aquiles Serdan'},{id:8, idm: 5, nombrem:'Ascension'},{id:8, idm: 6, nombrem:'Bachiniva'},
    {id:8, idm: 7, nombrem:'Balleza'},{id:8, idm: 8, nombrem:'Batopilas de Manuel Gomez Morin'},{id:8, idm: 9, nombrem:'Bocoyna'},
    {id:8, idm: 10, nombrem:'Buenaventura'},{id:8, idm: 11, nombrem:'Camargo'},{id:8, idm: 12, nombrem:'Carichi'},
    {id:8, idm: 13, nombrem:'Casas Grandes'},{id:8, idm: 14, nombrem:'Chihuahua'},{id:8, idm: 15, nombrem:'Chinipas'},
    {id:8, idm: 16, nombrem:'Coronado'},{id:8, idm: 17, nombrem:'Coyame del Sotol'},{id:8, idm: 18, nombrem:'Cuauhtemoc'},
    {id:8, idm: 19, nombrem:'Cusihuiriachi'},{id:8, idm: 20, nombrem:'Delicias'},{id:8, idm: 21, nombrem:'Dr. Belisario Dominguez'},
    {id:8, idm: 22, nombrem:'El Tule'},{id:8, idm: 23, nombrem:'Galeana'},{id:8, idm: 24, nombrem:'Gran Morelos'},
    {id:8, idm: 25, nombrem:'Guachochi'},{id:8, idm: 26, nombrem:'Guadalupe y Calvo'}, {id:8, idm: 27, nombrem:'Guadalupe'},
    {id:8, idm: 28, nombrem:'Guazapares'},{id:8, idm: 29, nombrem:'Guerrero'},{id:8, idm: 30, nombrem:'Gomez Farias'},
    {id:8, idm: 31, nombrem:'Hidalgo del Parral'},{id:8, idm: 32, nombrem:'Huejotitan'},{id:8, idm: 33, nombrem:'Ignacio Zaragoza'},
    {id:8, idm: 34, nombrem:'Janos'},{id:8, idm: 35, nombrem:'Jimenez'},{id:8, idm: 36, nombrem:'Julimes'},
    {id:8, idm: 37, nombrem:'Juarez'},{id:8, idm: 38, nombrem:'La Cruz'},{id:8, idm: 39, nombrem:'Lopez'},
    {id:8, idm: 40, nombrem:'Madera'},{id:8, idm: 41, nombrem:'Maguarichi'},{id:8, idm: 42, nombrem:'Manuel Benavides'},
    {id:8, idm: 43, nombrem:'Matachi'},{id:8, idm: 44, nombrem:'Matamoros'},{id:8, idm: 45, nombrem:'Meoqui'},
    {id:8, idm: 46, nombrem:'Morelos'},{id:8, idm: 47, nombrem:'Moris'},{id:8, idm: 48, nombrem:'Namiquipa'},
    {id:8, idm: 49, nombrem:'Nonoava'},{id:8, idm: 50, nombrem:'Nuevo Casas Grandes'},{id:8, idm: 51, nombrem:'Ocampo'},
    {id:8, idm: 52, nombrem:'Ojinaga'},{id:8, idm: 53, nombrem:'Praxedis G. Guerrero'},{id:8, idm: 54, nombrem:'Riva Palacio'},
    {id:8, idm: 55, nombrem:'Rosales'},{id:8, idm: 56, nombrem:'Rosario'},{id:8, idm: 57, nombrem:'San Francisco de Borja'},
    {id:8, idm: 58, nombrem:'San Francisco de Conchos'},{id:8, idm: 59, nombrem:'San Francisco del Oro'},{id:8, idm: 60, nombrem:'Santa Barbara'},
    {id:8, idm: 61, nombrem:'Santa Isabel'},{id:8, idm: 62, nombrem:'Satevo'},{id:8, idm: 63, nombrem:'Saucillo'},
    {id:8, idm: 64, nombrem:'Temosachic'},{id:8, idm: 65, nombrem:'Urique'},{id:8, idm: 66, nombrem:'Uruachi'},
    {id:8, idm: 67, nombrem:'Valle de Zaragoza'},
    //Ciudad de México
    {id:9, idm: 1, nombrem:'Alvaro Obregon'},{id:9, idm: 2, nombrem:'Azcapotzalco'},{id:9, idm: 3, nombrem:'Benito Juarez'},
    {id:9, idm: 4, nombrem:'Coyoacan'},{id:9, idm: 5, nombrem:'Cuajimalpa de Morelos'},{id:9, idm: 6, nombrem:'Cuauhtemoc'},
    {id:9, idm: 7, nombrem:'Gustavo A. Madero'},{id:9, idm: 8, nombrem:'Iztacalco'},{id:9, idm: 9, nombrem:'Iztapalapa'},
    {id:9, idm: 10, nombrem:'La Magdalena Contreras'},{id:9, idm: 11, nombrem:'Miguel Hidalgo'},{id:9, idm: 12, nombrem:'Milpa Alta'},
    {id:9, idm: 13, nombrem:'Tlalpan'},{id:9, idm: 14, nombrem:'Tlahuac'},{id:9, idm: 15, nombrem:'Venustiano Carranza'},
    {id:9, idm: 16, nombrem:'Xochimilco'},
    //Durango
    {id:10, idm:1, nombrem:'Canatlan'},{id:10, idm:2, nombrem:'Canelas'},{id:10, idm:3, nombrem:'Coneto de Comonfort'},
    {id:10, idm:4, nombrem:'Cuencame'},{id:10, idm:5, nombrem:'Durango'},{id:10, idm:6, nombrem:'El Oro'},
    {id:10, idm:7, nombrem:'General Simon Bolivar'},{id:10, idm:8, nombrem:'Gomez Palacio'},{id:10, idm:9, nombrem:'Guadalupe Victoria'},
    {id:10, idm:10, nombrem:'Guanacevi'},{id:10, idm:11, nombrem:'Hidalgo'},{id:10, idm:12, nombrem:'Inde'},
    {id:10, idm:13, nombrem:'Lerdo'},{id:10, idm:14, nombrem:'Mapimi'},{id:10, idm:15, nombrem:'Mezquital'},
    {id:10, idm:16, nombrem:'Nazas'},{id:10, idm:17, nombrem:'Nombre de Dios'},{id:10, idm:18, nombrem:'Nuevo Ideal'},
    {id:10, idm:19, nombrem:'Ocampo'},{id:10, idm:20, nombrem:'Otaez'},{id:10, idm:21, nombrem:'Panuco de Coronado'},
    {id:10, idm:22, nombrem:'Penon Blanco'},{id:10, idm:23, nombrem:'Poanas'},{id:10, idm:24, nombrem:'Pueblo Nuevo'},
    {id:10, idm:25, nombrem:'Rodeo'},{id:10, idm:26, nombrem:'San Bernardo'},{id:10, idm:27, nombrem:'San Dimas'},
    {id:10, idm:28, nombrem:'San Juan de Guadalupe'},{id:10, idm:29, nombrem:'San Juan del Rio'},{id:10, idm:30, nombrem:'San Luis del Cordero'},
    {id:10, idm:31, nombrem:'San Pedro del Gallo'},{id:10, idm:32, nombrem:'Santa Clara'},{id:10, idm:33, nombrem:'Santiago Papasquiaro'},
    {id:10, idm:34, nombrem:'Suchil'},{id:10, idm:35, nombrem:'Tamazula'},{id:10, idm:36, nombrem:'Tepehuanes'},
    {id:10, idm:37, nombrem:'Tlahualilo'},{id:10, idm:38, nombrem:'Topia'},{id:10, idm:39, nombrem:'Vicente Guerrero'},
    //Guerrero
    {id:11, idm:1, nombrem:'Acapulco de Juarez'},{id:11, idm:2, nombrem:'Acatepec'},{id:11, idm:3, nombrem:'Ahuacuotzingo'},
    {id:11, idm:4, nombrem:'Ajuchitlan del Progreso'},{id:11, idm:5, nombrem:'Alcozauca de Guerrero'},{id:11, idm:6, nombrem:'Alpoyeca'},
    {id:11, idm:7, nombrem:'Apaxtla'},{id:11, idm:8, nombrem:'Arcelia'},{id:11, idm:9, nombrem:'Atenango del Rio'},
    {id:11, idm:10, nombrem:'Atlamajalcingo del Monte'},{id:11, idm:11, nombrem:'Atlixtac'},{id:11, idm:12, nombrem:'Atoyac de Alvarez'},
    {id:11, idm:13, nombrem:'Ayutla de los Libres'},{id:11, idm:14, nombrem:'Azoyu'},{id:11, idm:15, nombrem:'Benito Juarez'},
    {id:11, idm:16, nombrem:'Buenavista de Cuellar'},{id:11, idm:17, nombrem:'Chilapa de Alvarez'},{id:11, idm:18, nombrem:'Chilpancingo de los Bravo'},
    {id:11, idm:19, nombrem:'Coahuayutla de Jose Maria Izazaga'},{id:11, idm:20, nombrem:'Cochoapa el Grande'},{id:11, idm:21, nombrem:'Cocula'},
    {id:11, idm:22, nombrem:'Copala'},{id:11, idm:23, nombrem:'Copalillo'},{id:11, idm:24, nombrem:'Copanatoyac'},
    {id:11, idm:25, nombrem:'Coyuca de Benitez'},{id:11, idm:26, nombrem:'Coyuca de Catalan'},{id:11, idm:27, nombrem:'Cuajinicuilapa'},
    {id:11, idm:28, nombrem:'Cualac'},{id:11, idm:29, nombrem:'Cuautepec'},{id:11, idm:30, nombrem:'Cuetzala del Progreso'},
    {id:11, idm:31, nombrem:'Cutzamala de Pinzon'},{id:11, idm:32, nombrem:'Eduardo Neri'},{id:11, idm:33, nombrem:'Florencio Villarreal'},
    {id:11, idm:34, nombrem:'General Canuto A. Neri'},{id:11, idm:35, nombrem:'General Heliodoro Castillo'},{id:11, idm:36, nombrem:'Huamuxtitlan'},
    {id:11, idm:37, nombrem:'Huitzuco de los Figueroa'},{id:11, idm:38, nombrem:'Iguala de la Independencia'},{id:11, idm:39, nombrem:'Igualapa'},
    {id:11, idm:40, nombrem:'Iliatenco'},{id:11, idm:41, nombrem:'Ixcateopan de Cuauhtemoc'},{id:11, idm:42, nombrem:'Jose Joaquin de Herrera'},
    {id:11, idm:43, nombrem:'Juan R. Escudero'},{id:11, idm:44, nombrem:'Juchitan'},{id:11, idm:45, nombrem:'La Union de Isidoro Montes de Oca'},
    {id:11, idm:46, nombrem:'Leonardo Bravo'},{id:11, idm:47, nombrem:'Malinaltepec'},{id:11, idm:48, nombrem:'Marquelia'},
    {id:11, idm:49, nombrem:'Martir de Cuilapan'},{id:11, idm:50, nombrem:'Metlatonoc'},{id:11, idm:51, nombrem:'Mochitlan'},
    {id:11, idm:52, nombrem:'Olinala'},{id:11, idm:53, nombrem:'Ometepec'},{id:11, idm:54, nombrem:'Pedro Ascencio Alquisiras'},
    {id:11, idm:55, nombrem:'Petatlan'},{id:11, idm:56, nombrem:'Pilcaya'},{id:11, idm:57, nombrem:'Pungarabato'},
    {id:11, idm:58, nombrem:'Quechultenango'},{id:11, idm:59, nombrem:'San Luis Acatlan'},{id:11, idm:60, nombrem:'San Marcos'},
    {id:11, idm:61, nombrem:'San Miguel Totolapan'},{id:11, idm:62, nombrem:'Taxco de Alarcon'},{id:11, idm:63, nombrem:'Tecoanapa'},
    {id:11, idm:64, nombrem:'Tecpan de Galeana'},{id:11, idm:65, nombrem:'Teloloapan'},{id:11, idm:66, nombrem:'Tepecoacuilco de Trujano'},
    {id:11, idm:67, nombrem:'Tetipac'},{id:11, idm:68, nombrem:'Tixtla de Guerrero'},{id:11, idm:69, nombrem:'Tlacoachistlahuaca'},
    {id:11, idm:70, nombrem:'Tlacoapa'},{id:11, idm:71, nombrem:'Tlalchapa'},{id:11, idm:72, nombrem:'Tlalixtaquilla de Maldonado'},
    {id:11, idm:73, nombrem:'Tlapa de Comonfort'},{id:11, idm:74, nombrem:'Tlapehuala'},{id:11, idm:75, nombrem:'Xalpatlahuac'},
    {id:11, idm:76, nombrem:'Xochihuehuetlan'},{id:11, idm:77, nombrem:'Xochistlahuaca'},{id:11, idm:78, nombrem:'Zapotitlan Tablas'},
    {id:11, idm:79, nombrem:'Zihuatanejo de Azueta'},{id:11, idm:80, nombrem:'Zirandaro'},{id:11, idm:81, nombrem:'Zitlala'},
    //Guanajuato
    {id:12, idm: 1, nombrem:'Abasolo' },{id:12, idm: 2, nombrem:'Acambaro' },{id:12, idm: 3, nombrem:'Apaseo el Alto' },
    {id:12, idm: 4, nombrem:'Apaseo el Grande' },{id:12, idm: 5, nombrem:'Atarjea' },{id:12, idm: 6, nombrem:'Celaya' },
    {id:12, idm: 7, nombrem:'Comonfort' },{id:12, idm: 8, nombrem:'Coroneo' },{id:12, idm: 9, nombrem:'Cortazar' },
    {id:12, idm: 10, nombrem:'Cueramaro' },{id:12, idm: 11, nombrem:'Doctor Mora' },{id:12, idm: 12, nombrem:'Dolores Hidalgo Cuna de la Independencia Nacional' },
    {id:12, idm: 13, nombrem:'Guanajuato' },{id:12, idm: 14, nombrem:'Huanimaro' },{id:12, idm: 15, nombrem:'Irapuato' },
    {id:12, idm: 16, nombrem:'Jaral del Progreso' },{id:12, idm: 17, nombrem:'Jerecuaro' },{id:12, idm: 18, nombrem:'Leon' },
    {id:12, idm: 19, nombrem:'Manuel Doblado' },{id:12, idm: 20, nombrem:'Moroleon' },{id:12, idm: 21, nombrem:'Ocampo' },
    {id:12, idm: 22, nombrem:'Penjamo' },{id:12, idm: 23, nombrem:'Pueblo Nuevo' },{id:12, idm: 24, nombrem:'Purisima del Rincon' },
    {id:12, idm: 25, nombrem:'Romita' },{id:12, idm: 26, nombrem:'Salamanca' },{id:12, idm: 27, nombrem:'Salvatierra' },
    {id:12, idm: 28, nombrem:'San Diego de la Union' },{id:12, idm: 29, nombrem:'San Felipe' },{id:12, idm: 30, nombrem:'San Francisco del Rincon' },
    //Hidalgo
    {id:13, idm: 1, nombrem:'Acatlan' },{id:13, idm: 2, nombrem:'Acaxochitlan' },{id:13, idm: 3, nombrem:'Actopan' },
    {id:13, idm: 4, nombrem:'Agua Blanca de Iturbide' },{id:13, idm: 5, nombrem:'Ajacuba' },{id:13, idm: 6, nombrem:'Alfajayucan' },
    {id:13, idm: 7, nombrem:'Almoloya' },{id:13, idm: 8, nombrem:'Apan' },{id:13, idm: 9, nombrem:'Atitalaquia' },
    {id:13, idm: 10, nombrem:'Atlapexco' },{id:13, idm: 11, nombrem:'Atotonilco de Tula' },{id:13, idm: 12, nombrem:'Atotonilco el Grande' },
    {id:13, idm: 13, nombrem:'Calnali' },{id:13, idm: 14, nombrem:'Cardonal' },{id:13, idm: 15, nombrem:'Chapantongo' },
    //Jalisco
    {id:14, idm:1, nombrem:'Acatic'},{id:14, idm:2, nombrem:'Acatlan de Juarez'},{id:14, idm:3, nombrem:'Ahualulco de Mercado'},
    {id:14, idm:4, nombrem:'Amacueca'},{id:14, idm:5, nombrem:'Amatitan'},{id:14, idm:6, nombrem:'Ameca'},
    {id:14, idm:7, nombrem:'Arandas'},{id:14, idm:8, nombrem:'Atemajac de Brizuela'},{id:14, idm:9, nombrem:'Atengo'},
    {id:14, idm:10, nombrem:'Atenguillo'},{id:14, idm:11, nombrem:'Atotonilco el Alto'},{id:14, idm:12, nombrem:'Atoyac'},
    {id:14, idm:13, nombrem:'Autlan de Navarro'},{id:14, idm:14, nombrem:'Ayotlan'},{id:14, idm:15, nombrem:'Ayutla'},
    //Michoacan
    {id:15, idm:1, nombrem:'Acuitzio'},{id:15, idm:2, nombrem:'Aguililla'},{id:15, idm:3, nombrem:'Alvaro Obregon'},
    {id:15, idm:4, nombrem:'Angamacutiro'},{id:15, idm:5, nombrem:'Angangueo'},{id:15, idm:6, nombrem:'Apatzingan'},
    {id:15, idm:7, nombrem:'Aporo'},{id:15, idm:8, nombrem:'Aquila'},{id:15, idm:9, nombrem:'Ario'},
    {id:15, idm:10, nombrem:'Arteaga'},{id:15, idm:11, nombrem:'Brisenas'},{id:15, idm:12, nombrem:'Buenavista'},
    {id:15, idm:13, nombrem:'Caracuaro'},{id:15, idm:14, nombrem:'Charapan'},{id:15, idm:15, nombrem:'Charo'},
    //Estado de México
    {id:16, idm: 1, nombrem:'Acambay de Ruiz Castaneda'},{id:16, idm: 2, nombrem:'Acolman'},{id:16, idm: 3, nombrem:'Aculco'},
    {id:16, idm: 4, nombrem:'Almoloya de Alquisiras'},{id:16, idm: 5, nombrem:'Almoloya de Juarez'},{id:16, idm: 6, nombrem:'Almoloya del Rio'},
    {id:16, idm: 7, nombrem:'Amanalco'},{id:16, idm: 8, nombrem:'Amatepec'},{id:16, idm: 9, nombrem:'Amecameca'},
    {id:16, idm: 10, nombrem:'Apaxco'},{id:16, idm: 11, nombrem:'Atenco'},{id:16, idm: 12, nombrem:'Atizapan de Zaragoza'},
    {id:16, idm: 13, nombrem:'Atizapan'},{id:16, idm: 14, nombrem:'Atlacomulco'},{id:16, idm: 15, nombrem:'Atlautla'},
    //Morelos
    {id:17, idm: 1, nombrem:'Amacuzac'},{id:17, idm: 2, nombrem:'Atlatlahucan'},{id:17, idm: 3, nombrem:'Axochiapan'},
    {id:17, idm: 4, nombrem:'Ayala'},{id:17, idm: 5, nombrem:'Coatlan del Rio'},{id:17, idm: 6, nombrem:'Cuautla'},
    {id:17, idm: 7, nombrem:'Cuernavaca'},{id:17, idm: 8, nombrem:'Emiliano Zapata'},{id:17, idm: 9, nombrem:'Huitzilac'},
    {id:17, idm: 10, nombrem:'Jantetelco'},{id:17, idm: 11, nombrem:'Jiutepec'},{id:17, idm: 12, nombrem:'Jojutla'},
    {id:17, idm: 13, nombrem:'Jonacatepec de Leandro Valle'},{id:17, idm: 14, nombrem:'Mazatepec'},{id:17, idm: 15, nombrem:'Miacatlan'},
    //Nayarit
    {id:18, idm: 1, nombrem:'Acaponeta'},{id:18, idm: 2, nombrem:'Ahuacatlan'},{id:18, idm: 3, nombrem:'Amatlan de Canas'},
    {id:18, idm: 4, nombrem:'Bahia de Banderas'},{id:18, idm: 5, nombrem:'Compostela'},{id:18, idm: 6, nombrem:'Del Nayar'},
    {id:18, idm: 7, nombrem:'Huajicori'},{id:18, idm: 8, nombrem:'Ixtlan del Rio'},{id:18, idm: 9, nombrem:'Jala'},
    {id:18, idm: 10, nombrem:'La Yesca'},{id:18, idm: 11, nombrem:'Rosamorada'},{id:18, idm: 12, nombrem:'Ruiz'},
    {id:18, idm: 13, nombrem:'San Blas'},{id:18, idm: 14, nombrem:'San Pedro Lagunillas'},{id:18, idm: 15, nombrem:'Santa Maria del Oro'},
    {id:18, idm: 16, nombrem:'Santiago Ixcuintla'},{id:18, idm: 17, nombrem:'Tecuala'},{id:18, idm: 18, nombrem:'Tepic'},
    {id:18, idm: 19, nombrem:'Tuxpan'},{id:18, idm: 20, nombrem:'Xalisco'},
    //Nuevo Leon
    {id:19, idm: 1, nombrem:'Abasolo'},{id:19, idm: 2, nombrem:'Agualeguas'},{id:19, idm: 3, nombrem:'Allende'},
    {id:19, idm: 4, nombrem:'Anahuac'},{id:19, idm: 5, nombrem:'Apodaca'},{id:19, idm: 6, nombrem:'Aramberri'},
    {id:19, idm: 7, nombrem:'Bustamante'},{id:19, idm: 8, nombrem:'Cadereyta Jimenez'},{id:19, idm: 9, nombrem:'Cerralvo'},
    {id:19, idm: 10, nombrem:'China'},{id:19, idm: 11, nombrem:'Cienega de Flores'},{id:19, idm: 12, nombrem:'Doctor Arroyo'},
    {id:19, idm: 13, nombrem:'Doctor Coss'},{id:19, idm: 14, nombrem:'Doctor Gonzalez'},{id:19, idm: 15, nombrem:'El Carmen'},
    //Oaxaca
    {id:20, idm: 1, nombrem:'Abejones'},{id:20, idm: 2, nombrem:'Acatlan de Perez Figueroa'},{id:20, idm: 3, nombrem:'Animas Trujano'},
    {id:20, idm: 4, nombrem:'Asuncion Cacalotepec'},{id:20, idm: 5, nombrem:'Asuncion Cuyotepeji'},{id:20, idm: 6, nombrem:'Asuncion Ixtaltepec'},
    {id:20, idm: 7, nombrem:'Asuncion Nochixtlan'},{id:20, idm: 8, nombrem:'Asuncion Ocotlan'},{id:20, idm: 9, nombrem:'Asuncion Tlacolulita'},
    {id:20, idm: 10, nombrem:'Ayoquezco de Aldama'},{id:20, idm: 11, nombrem:'Ayotzintepec'},{id:20, idm: 12, nombrem:'Calihuala'},
    {id:20, idm: 13, nombrem:'Candelaria Loxicha'},{id:20, idm: 14, nombrem:'Capulalpam de Mendez'},{id:20, idm: 15, nombrem:'Chahuites'},
    //Puebla
    {id:21, idm: 1, nombrem:'Acajete'},{id:21, idm: 2, nombrem:'Acateno'},{id:21, idm: 3, nombrem:'Acatlan'},
    {id:21, idm: 4, nombrem:'Acatzingo'},{id:21, idm: 5, nombrem:'Acteopan'},{id:21, idm: 6, nombrem:'Ahuacatlan'},
    {id:21, idm: 7, nombrem:'Ahuatlan'},{id:21, idm: 8, nombrem:'Ahuazotepec'},{id:21, idm: 9, nombrem:'Ahuehuetitla'},
    {id:21, idm: 10, nombrem:'Ajalpan'},{id:21, idm: 11, nombrem:'Albino Zertuche'},{id:21, idm: 12, nombrem:'Aljojuca'},
    {id:21, idm: 13, nombrem:'Altepexi'},{id:21, idm: 14, nombrem:'Amixtlan'},{id:21, idm: 15, nombrem:'Amozoc'},
    //Quintana Roo
    {id:22, idm: 1, nombrem:'Bacalar'},{id:22, idm: 2, nombrem:'Benito Juarez'},{id:22, idm: 3, nombrem:'Cozumel'},
    {id:22, idm: 4, nombrem:'Felipe Carrillo Puerto'},{id:22, idm: 5, nombrem:'Isla Mujeres'},{id:22, idm: 6, nombrem:'Jose Maria Morelos'},
    {id:22, idm: 7, nombrem:'Lazaro Cardenas'},{id:22, idm: 8, nombrem:'Othon P. Blanco'},{id:22, idm: 9, nombrem:'Puerto Morelos'},
    {id:22, idm: 10, nombrem:'Solidaridad'},{id:22, idm: 11, nombrem:'Tulum'},
    //Queretaro
    {id:23, idm: 1, nombrem:'Amealco de Bonfil'},{id:23, idm: 2, nombrem:'Arroyo Seco'},{id:23, idm: 3, nombrem:'Cadereyta de Montes'},
    {id:23, idm: 4, nombrem:'Colon'},{id:23, idm: 5, nombrem:'Corregidora'},{id:23, idm: 6, nombrem:'El Marques'},
    {id:23, idm: 7, nombrem:'Ezequiel Montes'},{id:23, idm: 8, nombrem:'Huimilpan'},{id:23, idm: 9, nombrem:'Jalpan de Serra'},
    {id:23, idm: 10, nombrem:'Landa de Matamoros'},{id:23, idm: 11, nombrem:'Pedro Escobedo'},{id:23, idm: 12, nombrem:'Penamiller'},
    {id:23, idm: 13, nombrem:'Pinal de Amoles'},{id:23, idm: 14, nombrem:'Queretaro'},{id:23, idm: 15, nombrem:'San Joaquin'},
    {id:23, idm: 16, nombrem:'San Juan del Rio'},{id:23, idm: 17, nombrem:'Tequisquiapan'},{id:23, idm: 18, nombrem:'Toliman'},
    //Sinaloa
    {id:24, idm: 1, nombrem:'Ahome'},{id:24, idm: 2, nombrem:'Angostura'},{id:24, idm: 3, nombrem:'Badiraguato'},
    {id:24, idm: 4, nombrem:'Choix'},{id:24, idm: 5, nombrem:'Concordia'},{id:24, idm: 6, nombrem:'Cosala'},
    {id:24, idm: 7, nombrem:'Culiacan'},{id:24, idm: 8, nombrem:'El Fuerte'},{id:24, idm: 9, nombrem:'Elota'},
    {id:24, idm: 10, nombrem:'Escuinapa'},{id:24, idm: 11, nombrem:'Guasave'},{id:24, idm: 12, nombrem:'Mazatlan'},
    {id:24, idm: 13, nombrem:'Mocorito'},{id:24, idm: 14, nombrem:'Navolato'},{id:24, idm: 15, nombrem:'Rosario'},
    {id:24, idm: 17, nombrem:'Salvador Alvarado'},{id:24, idm: 18, nombrem:'San Ignacio'},{id:24, idm: 19, nombrem:'Sinaloa'},
    //San Luis Potosi
    {id:25, idm: 1, nombrem:'Ahualulco'},{id:25, idm: 2, nombrem:'Alaquines'},{id:25, idm: 3, nombrem:'Aquismon'},
    {id:25, idm: 4, nombrem:'Armadillo de los Infante'},{id:25, idm: 5, nombrem:'Axtla de Terrazas'},{id:25, idm: 6, nombrem:'Cardenas'},
    {id:25, idm: 7, nombrem:'Catorce'},{id:25, idm: 8, nombrem:'Cedral'},{id:25, idm: 9, nombrem:'Cerritos'},
    {id:25, idm: 10, nombrem:'Cerro de San Pedro'},{id:25, idm: 11, nombrem:'Charcas'},{id:25, idm: 12, nombrem:'Ciudad Fernandez'},
    {id:25, idm: 13, nombrem:'Ciudad Valles'},{id:25, idm: 14, nombrem:'Ciudad del Maiz'},{id:25, idm: 15, nombrem:'Coxcatlan'},
    //Sonora
    {id:26, idm: 1, nombrem:'Aconchi'},{id:26, idm: 2, nombrem:'Agua Prieta'},{id:26, idm: 3, nombrem:'Alamos'},
    {id:26, idm: 4, nombrem:'Altar'},{id:26, idm: 5, nombrem:'Arivechi'},{id:26, idm: 6, nombrem:'Arizpe'},
    {id:26, idm: 7, nombrem:'Atil'},{id:26, idm: 8, nombrem:'Bacadehuachi'},{id:26, idm: 9, nombrem:'Bacanora'},
    {id:26, idm: 10, nombrem:'Bacerac'},{id:26, idm: 11, nombrem:'Bacoachi'},{id:26, idm: 12, nombrem:'Bacum'},
    {id:26, idm: 13, nombrem:'Banamichi'},{id:26, idm: 14, nombrem:'Baviacora'},{id:26, idm: 15, nombrem:'Bavispe'},
    //Tabasco
    {id:27, idm: 1, nombrem:'Balancan'},{id:27, idm: 2, nombrem:'Cardenas'},{id:27, idm: 3, nombrem:'Centla'},
    {id:27, idm: 4, nombrem:'Centro'},{id:27, idm: 5, nombrem:'Comalcalco'},{id:27, idm: 6, nombrem:'Cunduacan'},
    {id:27, idm: 7, nombrem:'Emiliano Zapata'},{id:27, idm: 8, nombrem:'Huimanguillo'},{id:27, idm: 9, nombrem:'Jalapa'},
    {id:27, idm: 10, nombrem:'Jalpa de Mendez'},{id:27, idm: 11, nombrem:'Jonuta'},{id:27, idm: 12, nombrem:'Macuspana'},
    {id:27, idm: 13, nombrem:'Nacajuca'},{id:27, idm: 14, nombrem:'Paraiso'},{id:27, idm: 15, nombrem:'Tacotalpa'},
    {id:27, idm: 16, nombrem:'Teapa'},{id:27, idm: 17, nombrem:'Tenosique'},
    //Tlaxcala
    {id:28, idm: 1, nombrem:'Acuamanala de Miguel Hidalgo'},{id:28, idm: 2, nombrem:'Amaxac de Guerrero'},{id:28, idm: 3, nombrem:'Apetatitlan de Antonio Carvajal'},
    {id:28, idm: 4, nombrem:'Apizaco'},{id:28, idm: 5, nombrem:'Atlangatepec'},{id:28, idm: 6, nombrem:'Atltzayanca'},
    {id:28, idm: 7, nombrem:'Benito Juarez'},{id:28, idm: 8, nombrem:'Calpulalpan'},{id:28, idm: 9, nombrem:'Chiautempan'},
    {id:28, idm: 10, nombrem:'Contla de Juan Cuamatzi'},{id:28, idm: 11, nombrem:'Cuapiaxtla'},{id:28, idm: 12, nombrem:'Cuaxomulco'},
    {id:28, idm: 13, nombrem:'El Carmen Tequexquitla'},{id:28, idm: 14, nombrem:'Emiliano Zapata'},{id:28, idm: 15, nombrem:'Espanita'},
    //Tamaulipas
    {id:29, idm: 1, nombrem:'Abasolo'},{id:29, idm: 2, nombrem:'Aldama'},{id:29, idm: 3, nombrem:'Altamira'},
    {id:29, idm: 4, nombrem:'Antiguo Morelos'},{id:29, idm: 5, nombrem:'Burgos'},{id:29, idm: 6, nombrem:'Bustamante'},
    {id:29, idm: 7, nombrem:'Camargo'},{id:29, idm: 8, nombrem:'Casas'},{id:29, idm: 9, nombrem:'Ciudad Madero'},
    {id:29, idm: 10, nombrem:'Cruillas'},{id:29, idm: 11, nombrem:'El Mante'},{id:29, idm: 12, nombrem:'Gomez Farias'},
    {id:29, idm: 13, nombrem:'Gonzalez'},{id:29, idm: 14, nombrem:'Guemez'},{id:29, idm: 15, nombrem:'Guerrero'},
    //Veracruz
    {id:30, idm: 1, nombrem:'Acajete'},{id:30, idm: 2, nombrem:'Acatlan'},{id:30, idm: 3, nombrem:'Acayucan'},
    {id:30, idm: 4, nombrem:'Actopan'},{id:30, idm: 5, nombrem:'Acula'},{id:30, idm: 6, nombrem:'Acultzingo'},
    {id:30, idm: 7, nombrem:'Agua Dulce'},{id:30, idm: 8, nombrem:'Alamo Temapache'},{id:30, idm: 9, nombrem:'Alpatlahuac'},
    {id:30, idm: 10, nombrem:'Alto Lucero de Gutierrez Barrios'},{id:30, idm: 11, nombrem:'Altotonga'},{id:30, idm: 12, nombrem:'Alvarado'},
    {id:30, idm: 13, nombrem:'Amatitlan'},{id:30, idm: 14, nombrem:'Amatlan de los Reyes'},{id:30, idm: 15, nombrem:'Angel R. Cabada'},
    //Yucatan
    {id:31, idm: 1, nombrem:'Abala'},{id:31, idm: 2, nombrem:'Acanceh'},{id:31, idm: 3, nombrem:'Akil'},
    {id:31, idm: 4, nombrem:'Baca'},{id:31, idm: 5, nombrem:'Bokoba'},{id:31, idm: 6, nombrem:'Buctzotz'},
    {id:31, idm: 7, nombrem:'Cacalchen'},{id:31, idm: 8, nombrem:'Calotmul'},{id:31, idm: 9, nombrem:'Cansahcab'},
    {id:31, idm: 10, nombrem:'Cantamayec'},{id:31, idm: 11, nombrem:'Celestun'},{id:31, idm: 12, nombrem:'Cenotillo'},
    {id:31, idm: 13, nombrem:'Chacsinkin'},{id:31, idm: 14, nombrem:'Chankom'},{id:31, idm: 15, nombrem:'Chapab'},
    //Zacatecas
    {id:32, idm: 1, nombrem:'Apozol'},{id:32, idm: 2, nombrem:'Apulco'},{id:32, idm: 3, nombrem:'Atolinga'},
    {id:32, idm: 4, nombrem:'Benito Juarez'},{id:32, idm: 5, nombrem:'Calera'},{id:32, idm: 6, nombrem:'Canitas de Felipe Pescador'},
    {id:32, idm: 7, nombrem:'Chalchihuites'},{id:32, idm: 8, nombrem:'Concepcion del Oro'},{id:32, idm: 9, nombrem:'Cuauhtemoc'},
    {id:32, idm: 10, nombrem:'El Plateado de Joaquin Amaro'},{id:32, idm: 11, nombrem:'El Salvador'},{id:32, idm: 12, nombrem:'Fresnillo'},
    {id:32, idm: 13, nombrem:'Genaro Codina'},{id:32, idm: 14, nombrem:'General Enrique Estrada'},{id:32, idm: 15, nombrem:'General Francisco R. Murguia'},
]

  getEstados(): registrointerface[]{
    return this.estados1;
  }
  getMunicipios(): municipiosinterface[]{
    return this.municipios1;
  }
  constructor() { }
}
